### ISSUE TITLE
system tests in CI

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#38]
I'll set up a github action workflow to run the output of teiphy with iqtree. @jjmccollum  - you can use that as an example for other programs like stemma and MrBayes.

**Comment by jjmccollum** [comment]
@rbturnbull I took a look at the error message for the iqtree test on `cicd`. Part of the problem is that the command

```bash
poetry run teiphy example/ubs_ephesians.xml example.nexus --states-present 
```

doesn't collapse any trivial readings, so we end up hitting the maximum of 64 symbols pretty quickly. To prevent this, the command should probably look more like

```bash
poetry run teiphy -t"reconstructed" -m"overlap" -m"lac" --states-present example/ubs_ephesians.xml example.nexus
```

or

```bash
poetry run teiphy -t"reconstructed" -t"defective" -t"orthographic" -m"overlap" -m"lac" --states-present example/ubs_ephesians.xml example.nexus
```

But the real problem that is causing IQTREE to complain is that some of the symbols are capital versions of earlier symbols, and IQTREE treats these as case-insensitive. This appears to be in compliance with the guidelines in Maddison, Swofford, and Maddison's paper on NEXUS (which notes that only symbols in the EQUATE block are case-sensitive), so I'll need to fix the code to use a different set of 64 ASCII symbols that are distinct up to capitalization. I should be able to take care of that tonight on the `cicd` branch. Then I can run the system test again and see if it works.

**Comment by rbturnbull** [comment]
i think the NEXUS standard is usually only loosely followed by the different phylogenetic software packages. The more flexible teiphy can be the better. I think an option to treat ambiguous states as missing is a good idea. Some packages might also will expect them with curly brackets in the data matrix as well instead of with an EQUATE symbol

**Comment by jjmccollum** [comment]
All right, in my latest push on `cicd`, I've commented out the code that generates the EQUATE symbols and writes the EQUATE block to NEXUS. Instead, I just write the ambiguous states with curly braces like you mentioned, as this requires fewer total symbols. The system test set up in `iqtree.yaml` now works on that branch, but I'll wait to merge that branch into `main` until we've implemented system tests for `stemma` and `mrbayes`.

**Comment by jjmccollum** [comment]
@rbturnbull Apologies for the long line of identical commits, but we now have a passing system test for `mrbayes` in place! That just leaves `stemma`, whose system test is currently failing at the install step. Here's the script I have at the moment:

```yaml
    - run: poetry install
    - name: Testing
      run: |
        poetry run teiphy -t reconstructed -t defective -t orthographic -m overlap -m lac -s"*" -s T --fill-correctors --format stemma example/ubs_ephesians.xml stemma_example
    - name: Install Phylogenetics Package
      run: |
        git clone https://github.com/stemmatic/stemma.git
        cd stemma
        make
    - name: Phylogenetics Run
      run: |
        stemma stemma_example
```

And here's the error I'm getting during installation:

```bash
cc -g -Wall  -O3          -c -o stemma.o stemma.c
cc -g -Wall  -O3          -c -o taxon.o taxon.c
cc -g -Wall  -O3          -c -o net.o net.c
cc -g -Wall  -O3          -c -o netmsg.o netmsg.c
cc -g -Wall  -O3          -c -o hyp.o hyp.c
cc -g -Wall  -O3          -c -o heur.o heur.c
cc -g -Wall  -O3          -c -o cache.o cache.c
cc -g -Wall  -O3          -c -o log.o log.c
cc -g -Wall  -O3          -c -o boot.o boot.c
cc -g -Wall  -O3          -c -o state.o state.c
cc   stemma.o taxon.o net.o netmsg.o hyp.o heur.o cache.o log.o boot.o state.o  -lm -o stemma
ln -f stemma /home/runner/bin/
ln: target '/home/runner/bin/' is not a directory: No such file or directory
make: *** [Makefile:25: /home/runner/bin/stemma] Error 1
Error: Process completed with exit code 2.
```

There seems to be an issue with the location of the `bin` directory in the Docker container. Any idea what could be causing this? And @stemmatic, does the script above look like it's doing the right thing, or are there additional steps I need to include?
